### ISSUE TITLE
Ctrl+C copying 1 million values slow -> prevent

### ISSUE THREAD

**Issue by bennyboer** [bennyboer/table-engine#12]
Prevent the user from selecting all cells using Ctrl+A and then copying via Ctrl+C since the ui will hang for a while.
Display a warning in the console and let the user only copy a maximum amount of cells (10000?).

**Comment by bennyboer** [comment]
We might need a user-provided notification service `ITableNotificationService` where we can delegate such notices like "User is trying to copy more than 10000 cells", so devs can display that to the user using their own SnackBar, Banner, whatever with i18n.

**Comment by bennyboer** [comment]
## TODO

- [ ] Add configuration to the table engine `maxCellCountToCopy` (or similar) - Default Value is `10000`
- [ ] Add `ITableNotificationService` to expose warnings to users in concrete table implementations (display in Snackbar, etc. is up to the developer)
- [ ] Add method to force copy despite the warning (Maybe the developer wants the users to copy after showing the warning if they really want to copy a lot of cells despite a possible lag)
